spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create-drop

blog:
  title: Blog
  banner:
    title: Warning
    content: The blog will be down tomorrow